include $(TOPDIR)/rules.mk

LUCI_TITLE:=Abox Addons
# comment for speedup build
#LUCI_DEPENDS:=+luci-compat +nginx
PKG_VERSION:=2.0.0
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature