name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.ver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        ver:
          - v23.05.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.ver }}
          FEEDNAME: abox
          KEY_BUILD: ${{ secrets.SIGN_PV_KEY }}
          V: s

      - name: Build images
        run: |
          pwd
          ls -R bin
          tar cvzf abox.tar.gz bin
          mkdir -p $GITHUB_WORKSPACE/targets/${{ matrix.arch }}
          sudo chown -R 1000:1000 $GITHUB_WORKSPACE/targets/${{ matrix.arch }}
          sudo chown -R 1000:1000 $GITHUB_WORKSPACE/bin/packages/${{ matrix.arch }}
          docker run --rm \
            -v $GITHUB_WORKSPACE/bin/packages/${{ matrix.arch }}/abox:/abox \
            -v $GITHUB_WORKSPACE/abox.pub:/abox.pub \
            -v $GITHUB_WORKSPACE/.github/workflows/build-image.sh:/build-image.sh \
            -v $GITHUB_WORKSPACE/targets/${{ matrix.arch }}:/builder/bin/targets \
            ghcr.io/junbou/imagebuilder:${{ matrix.arch}}-${{ matrix.ver }} \
            /build-image.sh ${{ matrix.ver }} ${{ matrix.arch}}
          sudo chown -R --reference=$GITHUB_WORKSPACE/targets/${{ matrix.arch }}/.. $GITHUB_WORKSPACE/targets/${{ matrix.arch }}
        shell: bash

      - name: Put Draft
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/heads/')
        with:
          draft: true
          files: |
            **/*-squashfs-combined.vhdx
            abox.tar.gz

      - name: Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            targets/${{ matrix.arch }}/**
