name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.ver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        ver:
          - 22.03.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build packages
        uses: openwrt/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.ver }}
          FEEDNAME: abox
          KEY_BUILD: ${{ secrets.SIGN_PV_KEY }}
          V: s

      - name: Build images
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/bin/packages/${{ matrix.arch }}/abox:/abox \
            -v $GITHUB_WORKSPACE/abox.pub:/abox.pub \
            -v $GITHUB_WORKSPACE/build-image.sh:/build-image.sh \
            ghcr.io/junwun/imagebuilder:${{ matrix.arch}}-${{ matrix.ver }} \
            /build-image.sh
        shell: bash

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/abox/*  