name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.ver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        ver:
          - v23.05.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.ver }}
          FEEDNAME: abox
          KEY_BUILD: ${{ secrets.SIGN_PV_KEY }}
          V: s

      - name: Build images
        run: |
          pwd
          ls -R bin
          tar cvzf abox.tar.gz bin
          sudo apt install -y build-essential libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils qemu-utils genisoimage
          .github/workflows/build-image.sh ${{ matrix.ver }} ${{ matrix.arch}}
        shell: bash

      - name: Put Draft
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/heads/')
        with:
          draft: true
          files: |
            **/*-squashfs-combined.vhdx
            abox.tar.gz

      - name: Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/bin/targets/**
