name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.sdk.ver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - ver: 22.03.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: openwrt/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk.ver }}
          KEY_BUILD: ${{ secrets.SIGN_PV_KEY }}
          V: s

      - name: Check output
        run: |
          ls -R .

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages/*.ipk