name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.ver }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        ver:
          - 22.03.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build packages
        uses: openwrt/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.ver }}
          FEEDNAME: abox
          KEY_BUILD: ${{ secrets.SIGN_PV_KEY }}
          V: s

      - name: Build images
        run: |
          mkdir -p $GITHUB_WORKSPACE/targets/${{ matrix.arch }}
          sudo chown -R 1000:1000 $GITHUB_WORKSPACE/targets/${{ matrix.arch }}
          sudo chown -R 1000:1000 $GITHUB_WORKSPACE/bin/packages/${{ matrix.arch }}
          docker run --rm \
            -v $GITHUB_WORKSPACE/bin/packages/${{ matrix.arch }}/abox:/abox \
            -v $GITHUB_WORKSPACE/abox.pub:/abox.pub \
            -v $GITHUB_WORKSPACE/.github/workflows/build-image.sh:/build-image.sh \
            -v $GITHUB_WORKSPACE/targets/${{ matrix.arch }}:/home/build/openwrt/bin/targets \
            ghcr.io/junwun/imagebuilder:${{ matrix.arch}}-${{ matrix.ver }} \
            /build-image.sh
          sudo chown -R --reference=$GITHUB_WORKSPACE/targets/${{ matrix.arch }}/.. $GITHUB_WORKSPACE/targets/${{ matrix.arch }}
        shell: bash

      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: targets/${{ matrix.arch }}/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            targets/${{ matrix.arch }}/*
